apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
  namespace: oficina
  labels:
    app.kubernetes.io/part-of: oficina-mecanica
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Logging__LogLevel__Default: "Information"
  Redis__ConnectionString: "oficina-redis:6379"
  NEW_RELIC_APP_NAME: "oficina-mecanica-api"
