apiVersion: v1
kind: Service
metadata:
  name: oficina-redis
  namespace: oficina
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: oficina-mecanica
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
